cryostatio/cryostat-helm

cryostat/README.md, cryostat/values.yaml
Backport of: #12 
Related to: #9
=> docs(readme): add section separator for other params

cryostat/values.schema.json
=> build(schema): add JSON schema for values

cryostat/Chart.yaml, cryostat/templates/tests/test-connection.yaml
=> test(health): test health endpoints for services

cryostat/Chart.yaml, cryostat/templates/NOTES.txt
This also fixes a typo in one of the branch conditions.
Fixes: #22
=> fix(notes): use code blocks for shell commands

cryostat/templates/deployment.yaml
=> fix(health): use /health/liveness for probes

cryostat/Chart.yaml, cryostat/values.yaml
=> chore(versions): set version tags for 2.2.0 release point

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/release-drafter.yml, .github/workflows/release-drafter.yml
Fixes #54
For issues templates: https://github.com/maxcao13/cryostat-helm/issues/new/choose
For a very barebones release drafter: see https://github.com/maxcao13/cryostat-helm/releases
=> chore(github): add pr + issue templates + add release drafter

cryostat/templates/deployment.yaml
=> fix(deploy): set CRYOSTAT_K8S_NAMESPACES

cryostat/Chart.yaml
=> chore(chart): use 2.3.1-dev for appVersion

ct.yaml
Related to #73 
This increases the timeout for the testing job.
=> fix(ci): increase timeout for chart testing process

.mergify.yml
fixes: #75 
Automatically add the safe-to-test label when reviewers open a pull request
=> feat(ci): safe-to-test

.github/workflows/submodule.yml
Backport of #79 for the `gh-pages` branch.
Fixes https://github.com/cryostatio/cryostat-helm/issues/78
=> ci(submodule): automatic update submodule on gh-pages push (#79)

.mergify.yml, charts/cryostat/Chart.yaml
Related to https://github.com/cryostatio/cryostat/issues/1695
=> build(release): prepare for cryostat 2.4.0 release

.github/workflows/ci.yml, .mergify.yml
=> feat(ci): allow cryostatio backport command

charts/cryostat/Chart.yaml
One other minor fix preventing the chart test from passing.
Fixes: #97
=> chore(version): change appVersion to 2.4.0-pre

.github/workflows/ci.yml
=> ci(test-action): upgrade chart-testing-action

charts/cryostat/templates/deployment.yaml
=> fix(s3): re-add env vars for S3 presigner for asset downloads

charts/cryostat/templates/deployment.yaml
Related to https://github.com/cryostatio/cryostat3/pull/290
=> fix(storage): pre-create eventtemplates bucket

charts/cryostat/templates/openshiftOauthProxy.tpl
See cryostatio/cryostat-operator#839
=> fix(proxy): do not pass unused credentials upstream

charts/cryostat/Chart.yaml
Related to #110 
Updated list of source code for helm chart: https://helm.sh/docs/topics/charts/#the-chartyaml-file
=> chore(chart): update chart sources

.github/workflows/push-oci.yml
- **ci(oci): skip release creation**
- **ci(oci): correct image name**
See #174 #173
=> ci(oci): correct image name and skip release creation

charts/cryostat/templates/deployment.yaml, charts/cryostat/tests/deployment_test.yaml
=> fix(db): correct hibernate config after Flyway introduction
