- cryostat/values.schema.json
Generated using readme-generator-for-helm, which also generates our README. I had to manually set the type for the items property of empty arrays. This was set to the empty string, but Helm doesn't seem to like that. Changing them to `object` fixed the issue.
Fixes: #18
> build(schema): add JSON schema for values

- cryostat/Chart.yaml
- cryostat/templates/tests/test-connection.yaml
This adds a test that queries the Cryostat health endpoint with curl and verifies some values with jq. It compares the `cryostatVersion` value to the Chart's appVersion. The `2.1.0-SNAPSHOT` builds from CI don't seem to have a tag associated with them. The `cryostatVersion` is simply `26d9450`. To simulate how this will work with the released 2.1.0 image, I built an image based off of a local `v2.1.0` tag, `helm-test-01`.
The test also queries the Grafana health endpoint as well.
To test:
```
helm install cryostat cryostat/ --set core.image.repository=quay.io/ebaron/cryostat,core.image.tag=helm-test-01
helm test cryostat --logs
```
Fixes: #16
> test(health): test health endpoints for services

- cryostat/Chart.yaml
Fixes #45 
Specified k8s version constraint in `Chart`.yaml. 
Reference: https://helm.sh/docs/topics/charts/#the-kubeversion-field
> chore(chart): specify kubeVersion constraints

- cryostat/Chart.yaml
Helm's `semverCompare` function does not seem to consider the [pre-release component](https://semver.org/#spec-item-9) in Semantic Versioning, unless explicitly specified in the comparison string. See: https://github.com/helm/helm/issues/10375
Fixes: #53
> fix(chart): consider pre-release versioning

- cryostat/templates/_helpers.tpl
- cryostat/templates/deployment.yaml
- cryostat/templates/secret.yaml
Fixes #62 
Prefix secret name with release's name to avoid conflicts with other releases in the same namespace.
> fix(secret): use release name in database secret

- cryostat/templates/NOTES.txt
Related to #66 
Update NOTES.txt to fix the incorrect field name in service spec.
> fix(note): fix incorrect service field in NOTES.txt

- .github/workflows/submodule.yml
Related to #71 
Fixes #78 
Add workflow to automatically update submodule on pushs (i.e. new releases).
**Notes: Require `${{ secrets.SUBMODULE_TOKEN }}` to push new commits**.
> ci(submodule): automatic update submodule on gh-pages push

- .github/workflows/submodule.yml
reference: [#916](https://github.com/cryostatio/cryostat-web/issues/916)
> build(ci): submodule should sign commits

- .github/workflows/helm-release.yml
- .github/workflows/submodule.yml
Won't fix the problem for this release unfortunately.
Fixes: #104
> ci(release): call submodule update from release workflow

- .github/workflows/helm-release.yml
Fixes #101 
- Upgraded chart-releaser-action to 1.6.0.
- Remove the redundant hard-coded chart-releaser version. This allows the action to select the version that is shipped with it.
> ci(release): upgrade chart-releaser-action to 1.6.0

- charts/cryostat/templates/deployment.yaml
Fixes #134 
Configure db and storage containers to use their respective security contexts. It's rather a quick fix.
> fix(psa): containers should use their dedicated security contexts

- charts/cryostat/templates/NOTES.txt
Related to #110 
Remove duplicate env var in release note for deployment patching command.
```bash
kubectl -n myns set env deploy --containers=cryostat cryostat QUARKUS_HTTP_HOST=$CRYOSTAT_WEB_HOST QUARKUS_HTTP_HOST=$CRYOSTAT_WEB_HOST STORAGE_EXT_URL=http://$CRYOSTAT_WEB_HOST:8080/storage/ GRAFANA_DASHBOARD_EXT_URL=http://$CRYOSTAT_WEB_HOST:8080/grafana/
```
```bash
kubectl -n myns set env deploy --containers=cryostat cryostat QUARKUS_HTTP_HOST=$CRYOSTAT_WEB_HOST STORAGE_EXT_URL=http://$CRYOSTAT_WEB_HOST:8080/storage/ GRAFANA_DASHBOARD_EXT_URL=http://$CRYOSTAT_WEB_HOST:8080/grafana/
```
> fix(notes): remove duplicate env var in release notes for clusterIP mode

- charts/cryostat/README.md
- charts/cryostat/values.yaml
Related to #124 
Small fix to add missing field name when using `@extra` annotation.
> docs(readme): add missing field name for extra annotation

- .github/workflows/ci.yml
- charts/cryostat/ci/minimal-deploy-values.yaml
- charts/cryostat/ci/non-minimal-deploy-values.yaml
- charts/cryostat/templates/_helpers.tpl
- charts/cryostat/templates/deployment.yaml
- charts/cryostat/templates/oauth2Proxy.tpl
- charts/cryostat/templates/service.yaml
- charts/cryostat/templates/serviceaccount.yaml
Related to #124 
- Wrapped new configurations in `()` for nil-checks. See [here](https://stackoverflow.com/questions/59795596/how-to-make-nested-variables-optional-in-helm/68807258#68807258).
- However, this is just for safe guarding, not solving the upgrade failures. See below.
- Create a wrapper that forces helm to use `--reset-then-reuse-values`. This is available only with helm 3.14+.
- The user cannot use `helm upgrade --reuse-values` as it would cause values such as `(.Values.storage).image.repository` to be empty. This is an invalid image repository.
- Helm 3.14+ has a new feature with `--reset-then-reuse-values`: https://github.com/helm/helm/pull/9653 that fits our upgrade path more.
- However, `chart-testing` has not been updated for accommodate that so this is a temporary fix.
- …
> fix(upgrade): fix errors during chart version upgrade

- charts/cryostat/templates/deployment.yaml
Depends on #127
Based on #127
See https://github.com/cryostatio/cryostat-storage/pull/14
Remove SeaweedFS volume tuning parameter overrides.
To test:
```bash
$ helm install cryostat --set authentication.openshift.enabled=true --set core.route.enabled=true --set openshiftOauthProxy.image.repository=quay.io/andrewazores/openshift-oauth-proxy --set openshiftOauthProxy.image.tag=test-14 --set authentication.basicAuth.enabled=true --set authentication.basicAuth.secretName=basicauth --set authentication.basicAuth.filename=htpasswd.conf --set storage.image.repository=quay.io/andrewazores/cryostat-storage --set storage.image.tag=volume-tuning-1 --set pvc.enabled=true --set pvc.storage=2Gi ./charts/cryostat/
```
This installs the Helm chart with an openshift-oauth-proxy (not actually required for …
> chore(storage): remove storage volume parameter overrides

- charts/cryostat/templates/NOTES.txt
- charts/cryostat/templates/deployment.yaml
- **fix(storage): remove unused STORAGE_EXT_URL env var**
- **use relative grafana dashboard ext url**
- **update post-install notes**
See https://github.com/cryostatio/cryostat-operator/pull/874
> fix(urls): use relative Grafana ext url, remove unused storage ext url

- charts/cryostat/templates/deployment.yaml
Related to #140 
Removed unused `containerPort` in Cryostat container's spec. The list is actually immutable but since deployment rollout strategy is `Recreate`, updating across upgrades is possible.
https://github.com/cryostatio/cryostat-helm/blob/4d14d68a9dfefd215ff5d0a2d014a6aa6014cb4b/charts/cryostat/templates/deployment.yaml#L12
```
$ oc explain pod.spec.containers.ports
KIND:       Pod
VERSION:    v1
FIELD: ports <[]ContainerPort>
DESCRIPTION:
List of ports to expose from the container. Not specifying a port here DOES
NOT prevent that port from being exposed. Any port which is listening on the
default "0.0.0.0" address inside a container will be accessible from the
network. Modifying this array with strategic merge patch may corrupt the
data. For more information See …
```
> chore(deployment): remove unused containerPort spec

- charts/cryostat/templates/service.yaml
Related to #159 
Related to #127
Un-exposed invalid port definition in Service (i.e. https port) that is not yet implemented on non-OpenShift environment.
```
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE    SELECTOR
cryostat     ClusterIP   10.110.17.206   <none>        8181/TCP   55s    app.kubernetes.io/instance=cryostat,app.kubernetes.io/name=cryostat
```
https://github.com/cryostatio/cryostat-helm/pull/159#discussion_r1671083612
> chore(service): https port should not be exposed on k8s environment

- charts/cryostat/Chart.yaml
Fixes #169 
Bumped min support k8s version to 1.25.0
See #169. The chart `version` should probably be `1.x` (See https://github.com/cryostatio/cryostat-helm/pull/159#discussion_r1674801222). But for backporting, that can be done in another PR ^^
> chore(kubeVersion): bump min support k8s version to 1.25.0

- charts/cryostat/Chart.yaml
Related to #159 
Bumped chart version to `2.0.0-dev`.
See https://github.com/cryostatio/cryostat-helm/pull/159#discussion_r1678378122
> chore(version): bump chart version to 2.0.0-dev

- .github/workflows/helm-release.yml
- .github/workflows/push-oci.yml
> ci(oci): push helm chart package to github container registry

- .github/workflows/push-oci.yml
> ci(oci): use standard token for pushing package

- .github/workflows/push-oci.yml
> ci(oci): attempt to push using only registry/namespace

- charts/cryostat/templates/NOTES.txt
- charts/cryostat/tests/notes_test.yaml
Related to #177, #160 
- Simplify post-install steps for ClusterIP service case.
- Use generic word `application` to refer to Cryostat in release notes. I suppose installing Cryostat chart already means installing Cryostat (See https://github.com/cryostatio/cryostat-helm/pull/177#issuecomment-2234258284)
When installing the chart without further customizations, the user just needs to port-forward the local port to the application pod. Previously, there were some extra steps that only defined some environment variables (i.e. not actually configuring cryostat).
```
helm install cryostat-sample charts/cryostat
```
Expected notes:
````
NOTES:
1. Configure the application to serve external traffic:
```
No actions required with this configuration.
```
2. Forward local port to the application's …
```
> chore(notes): simplify post-install steps for ClusterIP service case

- charts/cryostat/templates/alpha_config.yaml
- charts/cryostat/templates/deployment.yaml
- charts/cryostat/tests/alpha_config_test.yaml
- Added a condition to only create `alpha-config` ConfigMap when openshift authentication is not enabled (i.e. with OAuth2-Proxy).
- Added common labels to the generated ConfigMap. Just good practice for easy querying :D
I think it's a good to determine and create only necessary resources. This would be helpful in case the namespace has resource quota.
Related to #127
> fix(configmaps): skip creating configmap for Alpha Configurations when used with OCP Proxy

- charts/cryostat/templates/_helpers.tpl
- charts/cryostat/templates/_oauth2Proxy.tpl
- charts/cryostat/templates/_openshiftOauthProxy.tpl
- charts/cryostat/templates/cookie_secret.yaml
- charts/cryostat/tests/cookie_secret_test.yaml
- Added relevant cookie secret.
- Added test for cookie secret.
There was no cookie secret to be looked up in subsequent helm upgrade.
> fix(authproxy): cookie secret creation and reference using env valueFrom

- .github/workflows/chart-test.yml
- ct.bash
- k8s-test.bash
- **test(ct): add utility script for running ct locally**
- **add script for running connection tests**
> test(scripts): add scripts to ease local chart testing

- charts/cryostat/templates/NOTES.txt
- charts/cryostat/templates/cryostat_deployment.yaml
- charts/cryostat/templates/cryostat_service.yaml
- charts/cryostat/templates/db_deployment.yaml
- charts/cryostat/templates/db_service.yaml
- charts/cryostat/templates/reports_deployment.yaml
- charts/cryostat/templates/reports_service.yaml
- charts/cryostat/templates/storage_deployment.yaml
- charts/cryostat/templates/storage_service.yaml
- charts/cryostat/templates/tests/test-core-connection.yaml
- charts/cryostat/templates/tests/test-grafana-connection.yaml
- charts/cryostat/tests/cryostat_deployment_test.yaml
- charts/cryostat/tests/cryostat_service_test.yaml
- charts/cryostat/tests/db_deployment_test.yaml
- charts/cryostat/tests/db_service_test.yaml
- charts/cryostat/tests/notes_test.yaml
- charts/cryostat/tests/reports_deployment_test.yaml
- charts/cryostat/tests/storage_deployment_test.yaml
- charts/cryostat/tests/storage_service_test.yaml
Based on https://github.com/cryostatio/cryostat-helm/pull/191
Depends on https://github.com/cryostatio/cryostat-helm/pull/192
Fixes https://github.com/cryostatio/cryostat-helm/issues/194
> fix(selector): apply component labels/selectors

- charts/cryostat/templates/_helpers.tpl
- charts/cryostat/templates/cryostat_deployment.yaml
- charts/cryostat/templates/db_deployment.yaml
- charts/cryostat/templates/reports_deployment.yaml
- charts/cryostat/templates/storage_deployment.yaml
- charts/cryostat/tests/cryostat_deployment_test.yaml
- charts/cryostat/tests/db_deployment_test.yaml
- charts/cryostat/tests/reports_deployment_test.yaml
- charts/cryostat/tests/storage_deployment_test.yaml
Related to #200 
Related to #192 
Added a major version suffix to deployment such that breaking changes can recreate the deployment (i.e. selector changes)
I stopped short of doing the same for other resources since they might introduce more breaking behaviors than intended. Also, resources such as secrets and configmaps can (i think) still be reused from 3.x version for seamless upgrades :D
The CI runs on this PR do not actually reflect these changes (i.e. no immutable fields are updated). We will need to manually run the steps below to check :D
```console
$ helm search repo cryostat
NAME               	CHART VERSION	APP VERSION	DESCRIPTION                                       
cryostatio/cryostat	1.0.1        	3.0.1      	Securely manage JFR recordings for your contain...
$ helm …
```
> feat(template): add major version suffix to deployment names

- charts/cryostat/templates/_helpers.tpl
- charts/cryostat/templates/cryostat_service.yaml
- charts/cryostat/tests/cookie_secret_test.yaml
- charts/cryostat/tests/cryostat_deployment_test.yaml
- charts/cryostat/tests/cryostat_service_test.yaml
- charts/cryostat/tests/db_deployment_test.yaml
- charts/cryostat/tests/db_pvc_test.yaml
- charts/cryostat/tests/db_secret_test.yaml
- charts/cryostat/tests/db_service_test.yaml
- charts/cryostat/tests/reports_deployment_test.yaml
- charts/cryostat/tests/role_test.yaml
- charts/cryostat/tests/route_test.yaml
- charts/cryostat/tests/storage_deployment_test.yaml
- charts/cryostat/tests/storage_pvc_test.yaml
- charts/cryostat/tests/storage_secret_test.yaml
- charts/cryostat/tests/storage_service_test.yaml
- **feat(labels): add part-of selector label**
- **chore(service): rename ports to remove 'cryostat-' prefix**
Related to https://github.com/cryostatio/cryostat-openshift-console-plugin/issues/2
> feat(labels): add part-of selector label

- charts/cryostat/templates/db_deployment.yaml
- charts/cryostat/templates/reports_deployment.yaml
- charts/cryostat/templates/storage_deployment.yaml
- charts/cryostat/tests/cryostat_service_test.yaml
- charts/cryostat/tests/cryostat_tls_secret_test.yaml
- charts/cryostat/tests/db_deployment_test.yaml
- charts/cryostat/tests/reports_deployment_test.yaml
- charts/cryostat/tests/storage_deployment_test.yaml
Related to https://github.com/cryostatio/cryostat-helm/issues/220
To test:
1. `helm install cryostat ./charts/cryostat`
2. Follow post-install port-forwarding steps
3. Deploy another sample application.
4. Open Cryostat Web UI and click around. Everything should work as normal. Sample application should be discovered.
> fix(serviceaccount): non-Cryostat Pods run as default serviceaccount

- charts/cryostat/templates/networkpolicy_ingress.yaml
- charts/cryostat/templates/reports_deployment.yaml
- charts/cryostat/tests/networkpolicy_ingress_test.yaml
See also https://github.com/cryostatio/cryostat-operator/pull/1102
Related to https://github.com/cryostatio/cryostat/pull/856
To test:
1. deploy chart with `--set reports.replicas=1` (or more than 1) and `--set core.discovery.kubernetes.enabled=true --set core.discovery.kubernetes.namespaces='{apps1}'`
2. deploy sample application in `apps1`
3. open reports pod logs
4. open Cryostat UI, start a recording and request analysis of the sample application
5. verify that log messages appear in the reports pod indicating that it received the request for a presigned recording URL and processed it successfully
6. verify that the Cryostat UI updates with the analysis
> feat(reports): configure for reports presigned URL retrieval
